metrics: unregister gwVersion when time comes
Not critical for HTTP gateway itself, but asymmetric and causes panic on
attempt to perform tests with two AIO versions:

--- FAIL: TestIntegration (48.12s)
panic: duplicate metrics collector registration attempted [recovered]
        panic: duplicate metrics collector registration attempted

goroutine 5 [running]:
testing.tRunner.func1.2({0x1035fe0, 0xc00674db80})
        /usr/lib64/go/1.20/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/lib64/go/1.20/src/testing/testing.go:1529 +0x39f
panic({0x1035fe0, 0xc00674db80})
        /usr/lib64/go/1.20/src/runtime/panic.go:884 +0x213
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x113c8f3?, {0xc007063ac0?, 0x1, 0xf?})
        /home/rik/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:406 +0x85
github.com/prometheus/client_golang/prometheus.MustRegister(...)
        /home/rik/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:178
github.com/nspcc-dev/neofs-http-gw/metrics.stateMetrics.register({{0x1393af0?, 0xc0077786c0?}, 0xc000627448?})
        /home/rik/dev/neofs-http-gw/metrics/metrics.go:95 +0xfd
github.com/nspcc-dev/neofs-http-gw/metrics.NewGateMetrics(0x113bb40?, 0x7?)
        /home/rik/dev/neofs-http-gw/metrics/metrics.go:58 +0x45
github.com/nspcc-dev/neofs-http-gw.(*app).initMetrics(0xc0076248c0)
        /home/rik/dev/neofs-http-gw/app.go:213 +0x54
github.com/nspcc-dev/neofs-http-gw.newApp({0x138cf08, 0xc006d928c0}, {0xc005135cc8, 0x2, 0x0?})
        /home/rik/dev/neofs-http-gw/app.go:185 +0x1045
github.com/nspcc-dev/neofs-http-gw.runServer()
        /home/rik/dev/neofs-http-gw/integration_test.go:103 +0x125
github.com/nspcc-dev/neofs-http-gw.TestIntegration(0x0?)
        /home/rik/dev/neofs-http-gw/integration_test.go:78 +0x3fe
testing.tRunner(0xc000102680, 0x1261428)
        /usr/lib64/go/1.20/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/lib64/go/1.20/src/testing/testing.go:1629 +0x3ea

Signed-off-by: Roman Khimov <roman@nspcc.ru>